module "webservers" {
  source                   = "/home/afshaniram05/module/inst"
  name                     = var.name
  description              = var.description
  name1                    = var.name1
  port1                    = var.port1
  name2                    = var.name2
  port2                    = var.port2
  zone                     = var.zone
  name3                    = var.name3
  machine_type1            = var.machine_type1
  zone1                    = var.zone1
  tags1                    = var.tags1
  image1                   = var.image1
  interface1               = var.interface1
  network1                 = var.network1
  foo1                     = var.foo1
  metadata_startup_script1 = var.metadata_startup_script1
  name4                    = var.name4
  machine_type2            = var.machine_type2
  zone2                    = var.zone2
  tags2                    = var.tags2
  image2                   = var.image2
  interface2               = var.interface2
  network2                 = var.network2
  foo2                     = var.foo2
  metadata_startup_script2 = var.metadata_startup_script2
}
